### PR TITLE
Fix PHP 8 compatibility

### LINKED ISSUE #71: PHP 8.2 compatibility
Confirm PHP 8.2 compatibility.

### PR DESCRIPTION
**Pull request by kasparsd**
Fixes #71.

- Pull in the latest dev version of `phpcompatibility/php-compatibility` to check for PHP 8 issues.
- Update wpcs and apply the suggested fixes.
- Update local dev environment to use native Docker. Remove Vagrant support.

### CODE REVIEW

File: src/modules/word-count/module.php [hunk 1]
```diff
@@ -2,10 +2,9 @@
 
 class WidgetContextWordCount {
 
-	private static $instance;
```
Comment (kasparsd) [inline src/modules/word-count/module.php:5]: Wasn't referenced anywhere.

File: .github/workflows/test.yml [hunk 2]
```diff
@@ -32,7 +32,7 @@ jobs:
         run: npm run lint
 
       - name: Test
-        run: npm run test
+        run: composer test
```
Comment (kasparsd) [inline .github/workflows/test.yml:35]: The npm `test` script now runs things inside the Docker environment.

File: composer.json [hunk 3]
```diff
@@ -20,18 +20,22 @@
...
+      "dealerdirect/phpcodesniffer-composer-installer": true
     }
   },
   "require-dev": {
     "10up/wp_mock": "^0.2.0",
+    "dealerdirect/phpcodesniffer-composer-installer": "^1.0",
     "mockery/mockery": "^0.9.5",
     "php-coveralls/php-coveralls": "^2.4",
-    "phpcompatibility/php-compatibility": "^9.3",
+    "phpcompatibility/php-compatibility": "dev-develop as 9.99.99",
```
Comment (kasparsd) [inline composer.json:33]: Needed for PHP 8+ checks since it only lives in the `develop`.

File: docker-compose.yml [hunk 4]
```diff
@@ -3,7 +3,7 @@ version: '3'
 services:
 
   mysql:
-    image: mysql:5
+    image: mysql:8.0
```
Comment (kasparsd) [inline docker-compose.yml:6]: This supports arm machines now.

File: docker-compose.yml [hunk 5]
```diff
@@ -14,7 +14,7 @@ services:
       MYSQL_ROOT_PASSWORD: password
 
   wordpress:
-    image: wordpress:latest
+    image: wordpress:php7.4
```
Comment (kasparsd) [inline docker-compose.yml:17]: Lock to a known PHP version to support phpunit tests at the current version.
